-------------------------------------------------------------------------------
Test set: com.circuitbreaker.resilience4j.retry.RetryTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.29 s <<< FAILURE! - in com.circuitbreaker.resilience4j.retry.RetryTest
backendAShouldRetryThreeTimes  Time elapsed: 0.8 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting:
  "{
  "timestamp" : "2021-09-11T17:16:54.624+00:00",
  "path" : "/actuator/prometheus",
  "status" : 404,
  "error" : "Not Found",
  "message" : null,
  "requestId" : "311c56aa-2"
}"
to contain:
  "resilience4j_retry_calls_total{application="resilience4j-demo",kind="failed_with_retry",name="backend-a",} 1.0" 
	at com.circuitbreaker.resilience4j.retry.RetryTest.backendAShouldRetryThreeTimes(RetryTest.java:16)

